import cv2
import numpy as np
import os
import tempfile
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
import config

class Reporter:
    def __init__(self):
        # Resolve outputs/ relative to project root, not current working directory
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.output_dir = os.path.join(base, config.OUTPUT_DIR)
        os.makedirs(self.output_dir, exist_ok=True)  # create if missing
        self.page_w, self.page_h = A4

    def _save_temp_image(self, image, suffix=".jpg"):
        # Save OpenCV image to a temporary file for ReportLab to read
        temp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
        cv2.imwrite(temp.name, image)
        return temp.name

    def generate(self, img, mask, features, result, fruit):
        # Create output filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_{fruit}_{result}_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        # Create PDF canvas
        c = canvas.Canvas(filepath, pagesize=A4)

        # Draw content
        self._draw_header(c, fruit, result)
        self._draw_metrics(c, features, result)
        self._draw_images(c, img, mask)
        self._draw_footer(c)

        c.save()
        return filepath

    def _draw_header(self, c, fruit, result):
        # Title bar background
        c.setFillColor(colors.HexColor("#1a1a2e"))
        c.rect(0, self.page_h - 80, self.page_w, 80, fill=1, stroke=0)

        # Title text
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 20)
        c.drawString(40, self.page_h - 45, "Fruit Ripeness Assessment Report")

        # Subtitle — fruit and result
        c.setFont("Helvetica", 12)
        timestamp = datetime.now().strftime("%d %B %Y, %H:%M:%S")
        c.drawString(40, self.page_h - 65, f"Fruit: {fruit.capitalize()}   |   Result: {result}   |   {timestamp}")

    def _draw_metrics(self, c, features, result):
        # Section title
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(40, self.page_h - 120, "Assessment Metrics")

        # Metrics data
        metrics = [
            ("Ripeness Classification", result),
            ("Hue Mean", f"{features['hue_mean']:.2f}"),
            ("Saturation Mean", f"{features['sat_mean']:.2f}"),
            ("Blemish Ratio", f"{features['blemish_ratio']:.4f}"),
            ("Contrast", f"{features['contrast']:.4f}"),
            ("Homogeneity", f"{features['homogeneity']:.4f}"),
            ("Energy", f"{features['energy']:.4f}"),
            ("Correlation", f"{features['correlation']:.4f}"),
        ]

        # Draw each metric as a row
        y = self.page_h - 150
        for label, value in metrics:
            c.setFont("Helvetica-Bold", 11)
            c.setFillColor(colors.HexColor("#333333"))
            c.drawString(40, y, f"{label}:")
            c.setFont("Helvetica", 11)
            c.setFillColor(colors.black)
            c.drawString(220, y, str(value))
            y -= 22

    def _draw_images(self, c, img, mask):
        # Section title
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(40, self.page_h - 380, "Image Analysis")

        # Convert mask to BGR so it saves correctly
        mask_bgr = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)

        # Save images to temp files
        orig_path = self._save_temp_image(img)
        mask_path = self._save_temp_image(mask_bgr)

        # Draw original image
        c.drawImage(orig_path, 40, self.page_h - 620,
                    width=240, height=220, preserveAspectRatio=True)
        c.setFont("Helvetica", 10)
        c.drawString(40, self.page_h - 635, "Original Image")

        # Draw mask image
        c.drawImage(mask_path, 310, self.page_h - 620,
                    width=240, height=220, preserveAspectRatio=True)
        c.drawString(310, self.page_h - 635, "Segmentation Mask")

        # Cleanup temp files
        os.unlink(orig_path)
        os.unlink(mask_path)

    def _draw_footer(self, c):
        # Footer line
        c.setStrokeColor(colors.HexColor("#cccccc"))
        c.line(40, 40, self.page_w - 40, 40)

        # Footer text
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#888888"))
        c.drawString(40, 25, "Generated by Fruit Ripeness Assessment System — BMDS2133 Image Processing")

#Testing
if __name__ == "__main__":
    import os
    import sys
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    from modules.preprocessor import Preprocessor
    from modules.segmentor import segmentor
    from modules.feature_extractor import FeatureExtractor
    from modules.grader import Grader

    base     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    img_path = os.path.join(base, "data", "raw", "banana_ripe.jpg")

    img = cv2.imread(img_path)
    preprocessed = Preprocessor().preprocess(img)
    mask = segmentor().create_mask(preprocessed)
    features = FeatureExtractor().extract(preprocessed, mask)
    result = Grader().grade(features)

    r = Reporter()
    path = r.generate(img, mask, features, result, config.ACTIVE_FRUIT)
    print(f"Report saved to: {path}")